qsub -N r20210113f3fal_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fal --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fal --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fal --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fal --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fal --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fal --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fal --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fal --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fal --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fal --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fal --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fal --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fal --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fal --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fal --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fal --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fal --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fal --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fal --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fal --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fal --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fal --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fal --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fal_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fal --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fal --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fal --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fal --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fal --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fal --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f2fal_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fal --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fal --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fal --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fal --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fal --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fal --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f1fal_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fal --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups age_group_code location_code && sleep 0.25 &&
qsub -N r20210113f3fl_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3fl_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f2fl_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f1fl_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 --fourier-groups location_code && sleep 0.25 &&
qsub -N r20210113f3_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f3fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f2_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f2fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f1_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113f1fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f3_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f3_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f3fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 3 && sleep 0.25 &&
qsub -N r20210113f2_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f2_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f2fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 2 && sleep 0.25 &&
qsub -N r20210113f1_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113f1_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113f1fl --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta --use-Z-fourier --fourier-levels 1 && sleep 0.25 &&
qsub -N r20210113nof_male_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113nof --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_male_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113nof --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_male_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113nof --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_male_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113nof --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_male_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113nof --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_male_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex male --data-version 20210113 --model-version 20210113nof --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_female_0 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113nof --holdout 0 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_female_1 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113nof --holdout 1 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_female_2 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113nof --holdout 2 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_female_3 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113nof --holdout 3 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_female_4 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113nof --holdout 4 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
qsub -N r20210113nof_female_5 ~/repos/covidemr/exec/cluster_R_exec.sh ~/repos/covidemr/exec/03_ita_estimation_run.R --run-sex female --data-version 20210113 --model-version 20210113nof --holdout 5 --use-covs intercept year_cov tfr unemp socserv tax_brackets hc_access elevation temperature --use-Z-sta && sleep 0.25 &&
echo "~~~~~~~~~~~~ FIN ~~~~~~~~~~~~";