paths:
  raw_pop: '/ihme/homes/nathenry/ita_emr/pop/pop_all_by_province.csv'
  raw_deaths: '/ihme/homes/nathenry/ita_emr/deaths/comuni_giornaliero_30giugno.csv'
  raw_covars:
    tfr: '/ihme/homes/nathenry/ita_emr/covars/COVAR_tfr_2015_2018_province.csv'
    unemp: '/ihme/homes/nathenry/ita_emr/covars/COVAR_unemployment_2015_2019_province.csv'
    socserv: '/ihme/homes/nathenry/ita_emr/covars/COVAR_social_services_2015_2017_province.csv'
  prepped_data: '/ihme/homes/nathenry/ita_emr/prepped_data'
  model_results: '/ihme/homes/nathenry/ita_emr/model_results'
  shp_detailed: '/ihme/homes/nathenry/ita_emr/shp/Limiti01012020/ProvCM01012020/ProvCM01012020_WGS84.shp'
  shp_generalized: '/ihme/homes/nathenry/ita_emr/shp/Limiti01012020_g/ProvCM01012020_g/ProvCM01012020_g_WGS84.shp'
prepped_data_version: '20200818'
prepped_data_files:
  location_table: 'location_table.csv'
  population: 'prepped_pop.csv'
  deaths: 'prepped_deaths.csv'
  full_data: 'prepped_data_full.csv'
  shapefile: 'analysis_shp.RDS'
model_years: [2015, 2016, 2017, 2018, 2019, 2020]
age_cutoffs: [0, 15, 30, 45, 60, 75]
first_death_date: '2020-03-01' # In YYYY-MM-DD format
pop_identifiers: ['age_group_code','sex','year','location_code']
death_identifiers: ['age_group_code','sex','year','week','location_code']
covar_identifiers: ['year','location_code']
encoding: 'Latin-1'
