paths:
  raw_pop_dir: '/ihme/homes/nathenry/ita_emr/pop'
  raw_deaths: '/ihme/homes/nathenry/ita_emr/deaths/comuni_giornaliero_30giugno.csv'
  raw_covars:
    inf_mort: '/ihme/homes/nathenry/ita_emr/covars/COVAR_infant_mort_2015_2017_province.csv'
    soc_servs: '/ihme/homes/nathenry/ita_emr/covars/COVAR_social_services_spending_2015_2017.csv'
    income: '/ihme/homes/nathenry/ita_emr/covars/COVAR_LPREF_2015_2018.csv'
  prepped_data: '/ihme/homes/nathenry/ita_emr/prepped_data'
  model_results: '/ihme/homes/nathenry/ita_emr/model_results'
  shp_detailed: '/ihme/homes/nathenry/ita_emr/shp/Limiti01012020/ProvCM01012020/ProvCM01012020_WGS84.shp'
  shp_generalized: '/ihme/homes/nathenry/ita_emr/shp/Limiti01012020_g/ProvCM01012020_g/ProvCM01012020_g_WGS84.shp'
model_years: [2015, 2016, 2017, 2018, 2019, 2020]
age_cutoffs: [0, 15, 30, 45, 60, 75]
first_death_date: '2020-03-01' # In YYYY-MM-DD format
pop_identifiers: ['age_group_code','sex','year','location_code']
death_identifiers: ['age_group_code','sex','year','week',location_code']
covar_identifiers: ['year','location_code']
encoding: 'Latin-1'
