paths:
  raw_pop_dir: '/ihme/homes/nathenry/ita_emr/pop/pop_all_by_province.csv'
  raw_deaths: '/ihme/homes/nathenry/ita_emr/deaths/comuni_giornaliero_30giugno.csv'
  raw_covars:
    tfr: '/ihme/homes/nathenry/ita_emr/covars/COVAR_tfr_2015_2018_province.csv'
    unemp: '/ihme/homes/nathenry/ita_emr/covars/COVAR_unemployment_2015_2019_province.csv'
    socserv: '/ihme/homes/nathenry/ita_emr/covars/COVAR_social_services_2015_2017_province.csv'
  prepped_data: '/ihme/homes/nathenry/ita_emr/prepped_data'
  model_results: '/ihme/homes/nathenry/ita_emr/model_results'
  shp_detailed: '/ihme/homes/nathenry/ita_emr/shp/Limiti01012020/ProvCM01012020/ProvCM01012020_WGS84.shp'
  shp_generalized: '/ihme/homes/nathenry/ita_emr/shp/Limiti01012020_g/ProvCM01012020_g/ProvCM01012020_g_WGS84.shp'
  tmb_template: '/ihme/code/covid-19/users/nathenry/covidemr/src/mort_stwa.cpp'
prepped_data_files:
  location_table: 'location_table.csv'
  population: 'prepped_pop.csv'
  deaths: 'prepped_deaths.csv'
  full_data: 'prepped_data_full.csv'
  template: 'model_template.csv'
  shapefile_sf: 'analysis_shp_sf.RDS'
  shapefile_sp: 'analysis_shp_sp.RDS'
  adjacency_matrix: 'adjmat.RDS'
results_files:
  data_stack: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_data_stack.RDS'
  params_list: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_params_list.RDS'
  model_fit: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_model_fit.RDS'
  sdrep: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_sdrep.RDS'
  param_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_param_draws.csv'
  pred_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_pred_draws.csv'
  pred_summary: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_pred_summary.csv'
  excess_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_excess_draws.csv'
  excess_summary: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_excess_summary.csv'
model_years: [2015, 2016, 2017, 2018, 2019, 2020]
age_cutoffs: [0, 15, 45, 65]
model_week_range: [1, 27]
num_draws: 1000
first_death_date: '2020-03-01' # In YYYY-MM-DD format
pop_identifiers: ['age_group_code','sex','year','location_code']
death_identifiers: ['age_group_code','sex','year','week','location_code']
covar_identifiers: ['year','location_code']
encoding: 'Latin-1'
