paths:
  raw_pop_dir: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/pop_all_by_province.csv'
  pop_raster_layers: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/pop_raster/ita_{year}.tif'
  raw_deaths: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/deaths/comuni_giornaliero_dati_fino_31agosto.csv'
  raw_covid_deaths: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covid_deaths/Reference_hospitalization_all_locs.csv'
  raw_covars:
    tfr: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/COVAR_tfr_2015_2018_province.csv'
    unemp: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/COVAR_unemployment_2015_2019_province.csv'
    socserv: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/COVAR_social_services_2015_2017_province.csv'
    tax_brackets: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/COVAR_income_categories_by_muni_2015_2018.csv'
    tax_income: [
      '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/COVAR_income_totals_by_muni_2015_2018.csv',
      '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/COVAR_income_categories_by_muni_2015_2018.csv'
    ]
    hc_access: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/raster/healthcare_access.tif'
    elevation: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/raster/italy_DEM/30n000e_20101117_gmted_med150.tif'
    temperature: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/covars/meteostat_api_key.txt' # From dev.meteostat.net
  shp_detailed: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/shp/Limiti01012020/ProvCM01012020/ProvCM01012020_WGS84.shp'
  shp_generalized: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/shp/Limiti01012020_g/ProvCM01012020_g/ProvCM01012020_g_WGS84.shp'
  raw_location_codes: '/well/moore/users/bsb907/temp_data/ita_emr/raw_data/20201203/shp/location_codes.csv'
  prepped_data: '/well/moore/users/bsb907/temp_data/ita_emr/prepped_data'
  model_results: '/well/moore/users/bsb907/temp_data/ita_emr/model_results'
prepped_data_files:
  location_table: 'location_table.csv'
  population: 'prepped_pop.csv'
  pop_raster: 'pop_raster.tif'
  deaths: 'prepped_deaths.csv'
  covid_deaths: 'prepped_covid_deaths.csv'
  full_data: 'prepped_data_full.csv'
  full_data_rescaled: 'prepped_data_full_rescaled_covariates.csv'
  covars_list: 'prepared_covariates_list.RDS'
  covar_scaling_factors: 'covariate_scaling_factors.csv'
  template: 'model_template.csv'
  shapefile_sf: 'analysis_shp_sf.RDS'
  shapefile_sp: 'analysis_shp_sp.RDS'
  adjacency_matrix: 'adjmat.RDS'
results_files:
  data_stack: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_data_stack.RDS'
  params_list: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_params_list.RDS'
  map_glm_fit: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_map_glm_fit.RDS'
  model_fit: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_model_fit.RDS'
  sdrep: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_sdrep.RDS'
  param_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_param_draws.csv'
  pred_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_pred_draws.csv'
  pred_summary: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_pred_summary.csv'
  excess_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_excess_draws.csv'
  proportion_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_proportion_draws.csv'
  excess_summary: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_excess_summary.csv'
model_years: [2015, 2016, 2017, 2018, 2019, 2020]
age_cutoffs: [0, 15, 45, 65]
model_week_range: [1, 52]
num_draws: 1000
projection: "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs"
first_death_date: '2020-02-26' # In YYYY-MM-DD format
final_obs_date: '2020-08-31' # In YYYY-MM-DD format
pop_identifiers: ['age_group_code','sex','year','location_code']
death_identifiers: ['age_group_code','sex','year','week','location_code']
encoding: 'Latin-1'
