paths:
  raw_pop_dir: '~/temp_data/ita_emr/raw_data/20201026/pop_all_by_province.csv'
  pop_raster_layers: '~/temp_data/ita_emr/raw_data/20201026/pop_raster/ita_{year}.tif'
  raw_deaths: '~/temp_data/ita_emr/raw_data/20201026/deaths/comuni_giornaliero_30giugno.csv'
  raw_covars:
    tfr: '~/temp_data/ita_emr/raw_data/20201026/covars/COVAR_tfr_2015_2018_province.csv'
    unemp: '~/temp_data/ita_emr/raw_data/20201026/covars/COVAR_unemployment_2015_2019_province.csv'
    socserv: '~/temp_data/ita_emr/raw_data/20201026/covars/COVAR_social_services_2015_2017_province.csv'
    tax_brackets: '~/temp_data/ita_emr/raw_data/20201026/covars/COVAR_income_categories_by_muni_2015_2018.csv'
    tax_income: [
      '~/temp_data/ita_emr/raw_data/20201026/covars/COVAR_income_totals_by_muni_2015_2018.csv',
      '~/temp_data/ita_emr/raw_data/20201026/covars/COVAR_income_categories_by_muni_2015_2018.csv'
    ]
    hc_access: '~/temp_data/ita_emr/raw_data/20201026/covars/raster/healthcare_access.tif'
    elevation: '~/temp_data/ita_emr/raw_data/20201026/covars/raster/italy_DEM/30n000e_20101117_gmted_med150.tif'
    temperature: '~/temp_data/ita_emr/raw_data/20201026/covars/meteostat_api_key.txt' # From dev.meteostat.net
  shp_detailed: '~/temp_data/ita_emr/raw_data/20201026/shp/Limiti01012020/ProvCM01012020/ProvCM01012020_WGS84.shp'
  shp_generalized: '~/temp_data/ita_emr/raw_data/20201026/shp/Limiti01012020_g/ProvCM01012020_g/ProvCM01012020_g_WGS84.shp'
  prepped_data: '~/temp_data/ita_emr/prepped_data'
  model_results: '~/temp_data/ita_emr/model_results'
prepped_data_files:
  location_table: 'location_table.csv'
  population: 'prepped_pop.csv'
  pop_raster: 'pop_raster.tif'
  deaths: 'prepped_deaths.csv'
  full_data: 'prepped_data_full.csv'
  template: 'model_template.csv'
  shapefile_sf: 'analysis_shp_sf.RDS'
  shapefile_sp: 'analysis_shp_sp.RDS'
  adjacency_matrix: 'adjmat.RDS'
results_files:
  data_stack: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_data_stack.RDS'
  params_list: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_params_list.RDS'
  model_fit: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_model_fit.RDS'
  sdrep: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_sdrep.RDS'
  param_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_param_draws.csv'
  pred_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_pred_draws.csv'
  pred_summary: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_pred_summary.csv'
  excess_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_excess_draws.csv'
  proportion_draws: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_proportion_draws.csv'
  excess_summary: '{model_results_dir}/{model_run_version}/{run_sex}_{holdout}_excess_summary.csv'
model_years: [2015, 2016, 2017, 2018, 2019, 2020]
age_cutoffs: [0, 15, 45, 65]
model_week_range: [1, 52]
num_draws: 1000
projection: "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs"
first_death_date: '2020-03-01' # In YYYY-MM-DD format
pop_identifiers: ['age_group_code','sex','year','location_code']
death_identifiers: ['age_group_code','sex','year','week','location_code']
covar_identifiers: ['year','location_code']
encoding: 'Latin-1'
